name: clang-r416183b1

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull toolchain
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 aarch64-linux-android-4.9
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 arm-linux-androideabi-4.9
          mkdir clang && wget -O clang.tar.gz https://kali.download/nethunter-images/toolchains/clang-r416183b1.tar.gz
          tar -C clang/ -xf clang.tar.gz

      - name: Pull kernel source
        run: |
          git clone --depth=1 https://github.com/zhuiyight/nx6 kernel-source

      - name: Build kernel
        run: |
          export PATH=$GITHUB_WORKSPACE/clang/bin:${PATH}
          args="ARCH=arm64 \
                O=../out \
                CC=clang LD=ld.lld \
                CLANG_TRIPLE=aarch64-linux-gnu- \
                CROSS_COMPILE=$GITHUB_WORKSPACE/aarch64-linux-android-4.9/bin/aarch64-linux-android- \
                CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-"
          cd kernel-source
          make ${args} sdm845-NX616J-perf_defconfig
          make -j$(($(getconf _NPROCESSORS_ONLN) * 2)) ${args}

      - name: Upload kernel to artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: kernel-source/out/arch/arm64/boot/Image
